version: "3.1"

services:
  mongo:
    image: "mongo"
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo:/data/db
      - mongo_config:/data/configdb
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    ports:
      - 3050:3050
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      # Use this to connect to the Docker MongoDB container
      - DB_USER=root
      - DB_USER_PWD=password
      - DB_HOST=mongo:27017
      # use this variable to connect to something like MongoDB Atlas
      #- DB_URL="mongodb+srv://<username>:<password>@<host>/<database>?retryWrites=true&w=majority"
      - PORT=3050
      - TOKEN_KEY=secret
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    stdin_open: true
    ports:
      - 3000:3000
    volumes:
      #- /app/node_modules
      - ./client:/app
    environment:
      - REACT_APP_MAHABHARATH_API="http://localhost:3050"

volumes:
  mongo:
  mongo_config:
